import { collection, getDocs } from "firebase/firestore";
import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
// import styles from "../styles/Home.module.css";
import {
  Contact,
  Feature,
  Footer,
  Header,
  Hero,
  Steps,
  Testimonails,
} from "../components";
import { db } from "../firebase";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <Hero />
      <Steps />
      <Feature />
      <Testimonails />
      <Contact />
      <Footer />
    </div>
  );
}

// export async function getServerSideProps() {
//   const querySnapshot = await getDocs(collection(db, "cities"));

//   const data = querySnapshot.forEach((doc) => {
//     // doc.data() is never undefined for query doc snapshots
//     console.log(doc.id, " => ", doc.data());
//     return doc.data();
//   });
//   return {
//     props: { data }, // will be passed to the page component as props
//   };
// }
